services:
  postgres:
    image: postgres:16
    container_name: sui-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sui_indexer
    ports:
      - "5432:5432"
    volumes:
      - sui_postgres_data:/var/lib/postgresql/data

  indexer:
    build:
      context: ./indexer
    container_name: simple-sui-indexer
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/sui_indexer
    depends_on:
      - postgres

volumes:
  sui_postgres_data:
