services:
  postgres:
    image: postgres:14
    container_name: sui-postgres
    env_file:
      - ./postgres.env
    ports:
      - "5432:5432"
    volumes:
      - sui_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: simple-sui-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  indexer:
    build:
      context: ./indexer
    container_name: simple-sui-indexer
    env_file:
      - ./indexer/.env.postgres
    command:
      - "--remote-store-url"
      - "https://checkpoints.testnet.sui.io"
      - "--streaming-url"
      - "https://fullnode.testnet.sui.io:443"
    depends_on:
      - postgres

volumes:
  sui_postgres_data:
