services:
  postgres:
    image: postgres:16
    container_name: sui-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sui_indexer
    ports:
      - "5432:5432"
    volumes:
      - sui_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: simple-sui-backend
    environment:
      PORT: "8080"
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/sui_indexer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  indexer:
    build:
      context: ./indexer
    container_name: simple-sui-indexer
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/sui_indexer
    command:
      - "--remote-store-url"
      - "https://checkpoints.testnet.sui.io"
      - "--streaming-url"
      - "https://fullnode.testnet.sui.io:443"
    depends_on:
      - postgres

volumes:
  sui_postgres_data:
